### ISSUE TITLE
aiohttp version upgrade

### ISSUE THREAD

**Issue by ArynRama** [devoxin/Lavalink.py#141]
### Summary
when trying to install lavalink.py it tries to install a version of aiohttp which is unsupported by python 3.12

### Lavalink & System Version

OS: Windows
Python version: 3.12
Lavalink.py: 5.1.0

### Reproduction
run `pip install lavalink`

**Comment by devoxin** [comment]
The current state of affairs with aiohttp 3.9 is that I would sacrifice support for Python versions below 3.8. If I bump it now, I would need to slate it for a lavalink.py v6 release due to its breaking nature. For the time being, you can work around this by doing `pip install lavalink.py —no-dependencies`. Lavalink.py doesn't need any dependencies other than `aiohttp` anyway, so as long as you have the desired version of aiohttp installed, the library will just use that.

I shall keep this issue opened until a solution is pushed to the master branch, however there may not be any updates to this issue until a 6.0 release is ready, but with 5.0 still being relatively new, this may be a ways off.

**Comment by BazZziliuS** [comment]
You can make a beta release without aiohttp or with an updated one because poetry does not allow you to install without dependencies

**Comment by zlalvani** [comment]
This also prevents compatibility with other libraries (e.g. [hikari](https://github.com/hikari-py/hikari)) whose latest versions require a newer aiohttp version (>=3.9). 

FWIW Python3.7 reached EOL in 2023 and 3.8 will later this year so it's not unreasonable to drop support.
